/*CONFIGURATION*/
appsmode			= "devel";//devel or production
apps_version		= '1.0';
fg_source			= 'desktop';
if(appsmode=='devel'){
	api_url			= "http://akangaziz/pr/skyradar/v0.2/api/site/";
	socket_host		= "http://localhost:3000/";
}else{
	api_url			= "http://natari.co.id/skyradar/api/";
	socket_host		= "http://natari.co.id:3000/";
}

/*init global var */
processname			= '';
number				= '';
monthNames = [ "January", "February", "March", "April", "May", "June","July", "August", "September", "October", "November","December" ];
dayNames= ["Minggu","Senin","Selasa","Rabu","Kamis","Jumat","Sabtu"];

/*init data*/
airport	= {};
airport[1]	= [{
			   "fs": "CGK",
			   "iata": "CGK",
			   "icao": "WIII",
			   "name": "Soekarno-Hatta International Airport",
			   "city": "Jakarta",
			   "cityCode": "JKT",
			   "countryCode": "ID",
			   "countryName": "Indonesia",
			   "regionName": "Asia",
			   "timeZoneRegionName": "Asia/Jakarta",
			   "localTime": "2013-04-20T20:50:57.927",
			   "utcOffsetHours": 7,
			   "latitude": -6.130643,
			   "longitude": 106.655526,
			   "elevationFeet": 34,
			   "classification": 1,
			   "active": true,
			   "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/CGK?codeType=fs",
			   "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/CGK?codeType=fs"
			  },
			  {
			   "fs": "DPS",
			   "iata": "DPS",
			   "icao": "WRRR",
			   "name": "Ngurah Rai Airport",
			   "city": "Denpasar Bali",
			   "cityCode": "DPS",
			   "countryCode": "ID",
			   "countryName": "Indonesia",
			   "regionName": "Asia",
			   "timeZoneRegionName": "Asia/Makassar",
			   "localTime": "2013-04-20T21:50:57.924",
			   "utcOffsetHours": 8,
			   "latitude": -8.74446,
			   "longitude": 115.163304,
			   "elevationFeet": 14,
			   "classification": 2,
			   "active": true,
			   "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/DPS?codeType=fs",
			   "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/DPS?codeType=fs"
			  },
			  {
			   "fs": "MES",
			   "iata": "MES",
			   "icao": "WIMM",
			   "name": "Polonia Airport",
			   "city": "Medan",
			   "cityCode": "MES",
			   "countryCode": "ID",
			   "countryName": "Indonesia",
			   "regionName": "Asia",
			   "timeZoneRegionName": "Asia/Jakarta",
			   "localTime": "2013-04-20T20:50:57.924",
			   "utcOffsetHours": 7,
			   "latitude": 3.561111,
			   "longitude": 98.672778,
			   "elevationFeet": 90,
			   "classification": 3,
			   "active": true,
			   "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/MES?codeType=fs",
			   "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/MES?codeType=fs"
			  },
			  {
			   "fs": "BDO",
			   "iata": "BDO",
			   "icao": "WICC",
			   "name": "Husein Sastranegara Airport",
			   "city": "Bandung",
			   "cityCode": "BDO",
			   "countryCode": "ID",
			   "countryName": "Indonesia",
			   "regionName": "Asia",
			   "timeZoneRegionName": "Asia/Jakarta",
			   "localTime": "2013-04-20T20:50:57.927",
			   "utcOffsetHours": 7,
			   "latitude": -6.904648,
			   "longitude": 107.581779,
			   "elevationFeet": 2430,
			   "classification": 4,
			   "active": true,
			   "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BDO?codeType=fs",
			   "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BDO?codeType=fs"
			  },
			  {
			   "fs": "JOG",
			   "iata": "JOG",
			   "icao": "WIIJ",
			   "name": "Adisutjipto Airport",
			   "city": "Yogyakarta",
			   "cityCode": "JOG",
			   "countryCode": "ID",
			   "countryName": "Indonesia",
			   "regionName": "Asia",
			   "timeZoneRegionName": "Asia/Jakarta",
			   "localTime": "2013-04-21T00:51:24.526",
			   "utcOffsetHours": 7,
			   "latitude": -7.785572,
			   "longitude": 110.43706,
			   "elevationFeet": 350,
			   "classification": 3,
			   "active": true,
			   "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/JOG?codeType=fs",
			   "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/JOG?codeType=fs"
			  },
			  {
			   "fs": "SUB",
			   "iata": "SUB",
			   "icao": "WRSJ",
			   "name": "Juanda Airport",
			   "city": "Surabaya",
			   "cityCode": "SUB",
			   "countryCode": "ID",
			   "countryName": "Indonesia",
			   "regionName": "Asia",
			   "timeZoneRegionName": "Asia/Jakarta",
			   "localTime": "2013-04-21T00:51:24.526",
			   "utcOffsetHours": 7,
			   "latitude": -7.38387,
			   "longitude": 112.777234,
			   "elevationFeet": 9,
			   "classification": 2,
			   "active": true,
			   "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/SUB?codeType=fs",
			   "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/SUB?codeType=fs"
			  }
			  ]
			  ;
airport[2]	= [{
			   "fs": "XSP",
			   "iata": "XSP",
			   "icao": "WSSL",
			   "name": "Seletar Airport",
			   "city": "Singapore",
			   "cityCode": "SIN",
			   "countryCode": "SG",
			   "countryName": "Singapore",
			   "regionName": "Asia",
			   "timeZoneRegionName": "Asia/Singapore",
			   "localTime": "2013-04-21T01:38:03.796",
			   "utcOffsetHours": 8,
			   "latitude": 1.366667,
			   "longitude": 103.966667,
			   "elevationFeet": 35,
			   "classification": 4,
			   "active": true,
			   "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/XSP?codeType=fs",
			   "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/XSP?codeType=fs"
			  },
			  {
			   "fs": "SIN",
			   "iata": "SIN",
			   "icao": "WSSS",
			   "name": "Changi International Airport",
			   "city": "Singapore",
			   "cityCode": "SIN",
			   "countryCode": "SG",
			   "countryName": "Singapore",
			   "regionName": "Asia",
			   "timeZoneRegionName": "Asia/Singapore",
			   "localTime": "2013-04-21T01:38:03.796",
			   "utcOffsetHours": 8,
			   "latitude": 1.361173,
			   "longitude": 103.990201,
			   "elevationFeet": 22,
			   "classification": 1,
			   "active": true,
			   "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/SIN?codeType=fs",
			   "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/SIN?codeType=fs"
			  },
			  {
			   "fs": "QPG",
			   "iata": "QPG",
			   "icao": "WSAP",
			   "name": "Paya Lebar Airport",
			   "city": "Singapore",
			   "cityCode": "SIN",
			   "countryCode": "SG",
			   "countryName": "Singapore",
			   "regionName": "Asia",
			   "timeZoneRegionName": "Asia/Singapore",
			   "localTime": "2013-04-21T01:38:03.796",
			   "utcOffsetHours": 8,
			   "latitude": 1.35,
			   "longitude": 103.9,
			   "elevationFeet": 65,
			   "classification": 5,
			   "active": true,
			   "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/QPG?codeType=fs",
			   "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/QPG?codeType=fs"
			  },
			  {
			   "fs": "WSAG",
			   "icao": "WSAG",
			   "name": "Sembawang",
			   "city": "Singapore",
			   "countryCode": "SG",
			   "countryName": "Singapore",
			   "regionName": "Asia",
			   "timeZoneRegionName": "Asia/Singapore",
			   "localTime": "2013-04-21T01:38:03.796",
			   "utcOffsetHours": 8,
			   "latitude": 1.501149,
			   "longitude": 103.816667,
			   "elevationFeet": 86,
			   "classification": 5,
			   "active": true,
			   "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/WSAG?codeType=fs",
			   "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/WSAG?codeType=fs"
			  },
			  {
			   "fs": "TGA",
			   "iata": "TGA",
			   "icao": "WSAT",
			   "name": "Tengah",
			   "city": "Singapore",
			   "countryCode": "SG",
			   "countryName": "Singapore",
			   "regionName": "Asia",
			   "timeZoneRegionName": "Asia/Singapore",
			   "localTime": "2013-04-21T01:38:03.796",
			   "utcOffsetHours": 8,
			   "latitude": 1.426665,
			   "longitude": 103.780556,
			   "elevationFeet": 50,
			   "classification": 5,
			   "active": true,
			   "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/TGA?codeType=fs",
			   "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/TGA?codeType=fs"
			  }];
airport[3]	= [
			{
			   "fs": "JFK",
			   "iata": "JFK",
			   "icao": "KJFK",
			   "faa": "JFK",
			   "name": "John F. Kennedy International Airport",
			   "street1": "JFK Airport",
			   "city": "New York",
			   "cityCode": "NYC",
			   "stateCode": "NY",
			   "postalCode": "11430",
			   "countryCode": "US",
			   "countryName": "United States",
			   "regionName": "North America",
			   "timeZoneRegionName": "America/New_York",
			   "weatherZone": "NYZ178",
			   "localTime": "2013-04-20T13:40:18.958",
			   "utcOffsetHours": -4,
			   "latitude": 40.642335,
			   "longitude": -73.78817,
			   "elevationFeet": 13,
			   "classification": 1,
			   "active": true,
			   "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/JFK?codeType=fs",
			   "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/JFK?codeType=fs"
			  },
			  {
			   "fs": "TSS",
			   "iata": "TSS",
			   "name": "East 34th Street Heliport",
			   "city": "New York",
			   "cityCode": "NYC",
			   "stateCode": "NY",
			   "countryCode": "US",
			   "countryName": "United States",
			   "regionName": "North America",
			   "timeZoneRegionName": "America/New_York",
			   "localTime": "2013-04-20T13:40:19.040",
			   "utcOffsetHours": -4,
			   "latitude": 40.766667,
			   "longitude": -74.166667,
			   "classification": 5,
			   "active": true,
			   "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/TSS?codeType=fs",
			   "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/TSS?codeType=fs"
			  },
			  {
			   "fs": "LAX",
			   "iata": "LAX",
			   "icao": "KLAX",
			   "faa": "LAX",
			   "name": "Los Angeles International Airport",
			   "street1": "One World Way",
			   "street2": "",
			   "city": "Los Angeles",
			   "cityCode": "LAX",
			   "stateCode": "CA",
			   "postalCode": "90045-5803",
			   "countryCode": "US",
			   "countryName": "United States",
			   "regionName": "North America",
			   "timeZoneRegionName": "America/Los_Angeles",
			   "weatherZone": "CAZ041",
			   "localTime": "2013-04-20T10:40:18.957",
			   "utcOffsetHours": -7,
			   "latitude": 33.943399,
			   "longitude": -118.408279,
			   "elevationFeet": 126,
			   "classification": 1,
			   "active": true,
			   "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/LAX?codeType=fs",
			   "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/LAX?codeType=fs"
			  }
			  ]
			  ;		
airport[4]	= [{
			   "fs": "PEK",
			   "iata": "PEK",
			   "icao": "ZBAA",
			   "name": "Beijing Capital International Airport",
			   "street1": "Capital Airport Rd",
			   "city": "Beijing",
			   "cityCode": "BJS",
			   "countryCode": "CN",
			   "countryName": "China",
			   "regionName": "Asia",
			   "timeZoneRegionName": "Asia/Shanghai",
			   "localTime": "2013-04-21T01:44:38.731",
			   "utcOffsetHours": 8,
			   "latitude": 40.078538,
			   "longitude": 116.587095,
			   "elevationFeet": 115,
			   "classification": 1,
			   "active": true,
			   "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/PEK?codeType=fs",
			   "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/PEK?codeType=fs"
			  },
			  {
			   "fs": "WUH",
			   "iata": "WUH",
			   "icao": "ZHHH",
			   "name": "Wuhan Airport",
			   "street1": "Tianhe St",
			   "city": "Wuhan",
			   "cityCode": "WUH",
			   "countryCode": "CN",
			   "countryName": "China",
			   "regionName": "Asia",
			   "timeZoneRegionName": "Asia/Shanghai",
			   "localTime": "2013-04-21T01:44:38.731",
			   "utcOffsetHours": 8,
			   "latitude": 30.776598,
			   "longitude": 114.209625,
			   "elevationFeet": 115,
			   "classification": 2,
			   "active": true,
			   "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/WUH?codeType=fs",
			   "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/WUH?codeType=fs"
			  },
			  {
			   "fs": "HGH",
			   "iata": "HGH",
			   "icao": "ZSHC",
			   "name": "Hangzhou Xiaoshan International Airport",
			   "street1": "14th Rd",
			   "city": "Hangzhou",
			   "cityCode": "HGH",
			   "countryCode": "CN",
			   "countryName": "China",
			   "regionName": "Asia",
			   "timeZoneRegionName": "Asia/Shanghai",
			   "localTime": "2013-04-21T01:44:38.731",
			   "utcOffsetHours": 8,
			   "latitude": 30.236934,
			   "longitude": 120.432356,
			   "elevationFeet": 20,
			   "classification": 2,
			   "active": true,
			   "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/HGH?codeType=fs",
			   "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/HGH?codeType=fs"
			  },
			  {
			   "fs": "CSX",
			   "iata": "CSX",
			   "icao": "ZGHA",
			   "name": "Changsha Airport",
			   "street1": "Changsha Ave",
			   "city": "Changsha",
			   "cityCode": "CSX",
			   "countryCode": "CN",
			   "countryName": "China",
			   "regionName": "Asia",
			   "timeZoneRegionName": "Asia/Shanghai",
			   "localTime": "2013-04-21T01:44:38.731",
			   "utcOffsetHours": 8,
			   "latitude": 28.193336,
			   "longitude": 113.214592,
			   "elevationFeet": 217,
			   "classification": 2,
			   "active": true,
			   "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/CSX?codeType=fs",
			   "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/CSX?codeType=fs"
			  },
			  {
			   "fs": "SHA",
			   "iata": "SHA",
			   "icao": "ZSSS",
			   "name": "Shanghai Hongqiao International Airport",
			   "street1": "700 Yingbin 1st Rd",
			   "city": "Shanghai",
			   "cityCode": "SHA",
			   "countryCode": "CN",
			   "countryName": "China",
			   "regionName": "Asia",
			   "timeZoneRegionName": "Asia/Shanghai",
			   "localTime": "2013-04-21T01:44:38.731",
			   "utcOffsetHours": 8,
			   "latitude": 31.196815,
			   "longitude": 121.341976,
			   "elevationFeet": 10,
			   "classification": 1,
			   "active": true,
			   "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/SHA?codeType=fs",
			   "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/SHA?codeType=fs"
			  },
			  {
			   "fs": "FOC",
			   "iata": "FOC",
			   "icao": "ZSFZ",
			   "name": "Changle International Airport",
			   "street1": "Changye Rd",
			   "city": "Fuzhou",
			   "cityCode": "FOC",
			   "countryCode": "CN",
			   "countryName": "China",
			   "regionName": "Asia",
			   "timeZoneRegionName": "Asia/Shanghai",
			   "localTime": "2013-04-21T01:44:38.731",
			   "utcOffsetHours": 8,
			   "latitude": 25.931231,
			   "longitude": 119.66923,
			   "elevationFeet": 46,
			   "classification": 2,
			   "active": true,
			   "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/FOC?codeType=fs",
			   "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/FOC?codeType=fs"
			  },
			  {
			   "fs": "URC",
			   "iata": "URC",
			   "icao": "ZWWW",
			   "name": "Urumqi Airport",
			   "street1": "Airport Expressway Entrance & Wuchang Hwy",
			   "city": "Urumqi",
			   "cityCode": "URC",
			   "countryCode": "CN",
			   "countryName": "China",
			   "regionName": "Asia",
			   "timeZoneRegionName": "Asia/Shanghai",
			   "localTime": "2013-04-21T01:44:38.731",
			   "utcOffsetHours": 8,
			   "latitude": 43.90126,
			   "longitude": 87.475148,
			   "elevationFeet": 2126,
			   "classification": 2,
			   "active": true,
			   "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/URC?codeType=fs",
			   "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/URC?codeType=fs"
			  },
			  {
			   "fs": "XIY",
			   "iata": "XIY",
			   "icao": "ZLXY",
			   "name": "Xianyang Airport",
			   "street1": "Airport Ave",
			   "city": "Xian",
			   "cityCode": "SIA",
			   "countryCode": "CN",
			   "countryName": "China",
			   "regionName": "Asia",
			   "timeZoneRegionName": "Asia/Shanghai",
			   "localTime": "2013-04-21T01:44:38.731",
			   "utcOffsetHours": 8,
			   "latitude": 34.441156,
			   "longitude": 108.756053,
			   "elevationFeet": 1572,
			   "classification": 1,
			   "active": true,
			   "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/XIY?codeType=fs",
			   "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/XIY?codeType=fs"
			  },
			  {
			   "fs": "CGO",
			   "iata": "CGO",
			   "icao": "ZHCC",
			   "name": "Zhengzhou Airport",
			   "street1": "Ping'an Rd",
			   "city": "Zhengzhou",
			   "cityCode": "CGO",
			   "countryCode": "CN",
			   "countryName": "China",
			   "regionName": "Asia",
			   "timeZoneRegionName": "Asia/Shanghai",
			   "localTime": "2013-04-21T01:44:38.731",
			   "utcOffsetHours": 8,
			   "latitude": 34.527519,
			   "longitude": 113.840242,
			   "elevationFeet": 495,
			   "classification": 2,
			   "active": true,
			   "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/CGO?codeType=fs",
			   "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/CGO?codeType=fs"
			  }
			  ]
			  ;		
airport[5]	= [{
					   "fs": "SZB",
					   "iata": "SZB",
					   "icao": "WMSA",
					   "name": "Sultan Abdul Aziz Shah Airport",
					   "city": "Kuala Lumpur",
					   "cityCode": "KUL",
					   "countryCode": "MY",
					   "countryName": "Malaysia",
					   "regionName": "Asia",
					   "timeZoneRegionName": "Asia/Kuala_Lumpur",
					   "localTime": "2013-04-21T01:46:30.223",
					   "utcOffsetHours": 8,
					   "latitude": 3.130644,
					   "longitude": 101.558078,
					   "elevationFeet": 89,
					   "classification": 3,
					   "active": true,
					   "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/SZB?codeType=fs",
					   "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/SZB?codeType=fs"
					  },
					  {
					   "fs": "KUL",
					   "iata": "KUL",
					   "icao": "WMKK",
					   "name": "Kuala Lumpur International Airport",
					   "city": "Kuala Lumpur",
					   "cityCode": "KUL",
					   "countryCode": "MY",
					   "countryName": "Malaysia",
					   "regionName": "Asia",
					   "timeZoneRegionName": "Asia/Kuala_Lumpur",
					   "localTime": "2013-04-21T01:46:30.223",
					   "utcOffsetHours": 8,
					   "latitude": 2.755672,
					   "longitude": 101.70539,
					   "elevationFeet": 70,
					   "classification": 1,
					   "active": true,
					   "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/KUL?codeType=fs",
					   "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/KUL?codeType=fs"
					  },
					  {
					   "fs": "LBU",
					   "iata": "LBU",
					   "icao": "WBKL",
					   "name": "Labuan Airport",
					   "city": "Labuan",
					   "cityCode": "LBU",
					   "countryCode": "MY",
					   "countryName": "Malaysia",
					   "regionName": "Asia",
					   "timeZoneRegionName": "Asia/Kuala_Lumpur",
					   "localTime": "2013-04-21T01:46:30.223",
					   "utcOffsetHours": 8,
					   "latitude": 5.294355,
					   "longitude": 115.249164,
					   "elevationFeet": 101,
					   "classification": 4,
					   "active": true,
					   "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/LBU?codeType=fs",
					   "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/LBU?codeType=fs"
					  },
					  {
					   "fs": "BKI",
					   "iata": "BKI",
					   "icao": "WBKK",
					   "name": "Kota Kinabalu Airport",
					   "city": "Kota Kinabalu",
					   "cityCode": "BKI",
					   "countryCode": "MY",
					   "countryName": "Malaysia",
					   "regionName": "Asia",
					   "timeZoneRegionName": "Asia/Kuala_Lumpur",
					   "localTime": "2013-04-21T01:46:30.223",
					   "utcOffsetHours": 8,
					   "latitude": 5.923961,
					   "longitude": 116.050753,
					   "elevationFeet": 10,
					   "classification": 2,
					   "active": true,
					   "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BKI?codeType=fs",
					   "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BKI?codeType=fs"
					  },
					  {
					   "fs": "KUA",
					   "iata": "KUA",
					   "icao": "WMKD",
					   "name": "Kuantan Airport",
					   "city": "Kuantan",
					   "cityCode": "KUA",
					   "countryCode": "MY",
					   "countryName": "Malaysia",
					   "regionName": "Asia",
					   "timeZoneRegionName": "Asia/Kuala_Lumpur",
					   "localTime": "2013-04-21T01:46:30.223",
					   "utcOffsetHours": 8,
					   "latitude": 3.780765,
					   "longitude": 103.215182,
					   "elevationFeet": 58,
					   "classification": 4,
					   "active": true,
					   "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/KUA?codeType=fs",
					   "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/KUA?codeType=fs"
					  },
					  {
					   "fs": "IPH",
					   "iata": "IPH",
					   "icao": "WMKI",
					   "name": "Ipoh Airport",
					   "city": "Ipoh",
					   "cityCode": "IPH",
					   "countryCode": "MY",
					   "countryName": "Malaysia",
					   "regionName": "Asia",
					   "timeZoneRegionName": "Asia/Kuala_Lumpur",
					   "localTime": "2013-04-21T01:46:30.224",
					   "utcOffsetHours": 8,
					   "latitude": 4.566944,
					   "longitude": 101.095833,
					   "elevationFeet": 130,
					   "classification": 4,
					   "active": true,
					   "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/IPH?codeType=fs",
					   "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/IPH?codeType=fs"
					  },
					  {
					   "fs": "JHB",
					   "iata": "JHB",
					   "icao": "WMKJ",
					   "name": "Sultan Ismail International Airport",
					   "city": "Johor Bharu",
					   "cityCode": "JHB",
					   "countryCode": "MY",
					   "countryName": "Malaysia",
					   "regionName": "Asia",
					   "timeZoneRegionName": "Asia/Kuala_Lumpur",
					   "localTime": "2013-04-21T01:46:30.224",
					   "utcOffsetHours": 8,
					   "latitude": 1.638889,
					   "longitude": 103.670833,
					   "elevationFeet": 135,
					   "classification": 4,
					   "active": true,
					   "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/JHB?codeType=fs",
					   "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/JHB?codeType=fs"
					  },
					  {
					   "fs": "KCH",
					   "iata": "KCH",
					   "icao": "WBGG",
					   "name": "Kuching Airport",
					   "city": "Kuching",
					   "cityCode": "KCH",
					   "countryCode": "MY",
					   "countryName": "Malaysia",
					   "regionName": "Asia",
					   "timeZoneRegionName": "Asia/Kuala_Lumpur",
					   "localTime": "2013-04-21T01:46:30.224",
					   "utcOffsetHours": 8,
					   "latitude": 1.484167,
					   "longitude": 110.340833,
					   "elevationFeet": 89,
					   "classification": 3,
					   "active": true,
					   "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/KCH?codeType=fs",
					   "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/KCH?codeType=fs"
					  }]
			  ;		
		
airport[6]	= [{
			   "fs": "BER",
			   "iata": "BER",
			   "name": "Berlin Brandenburg Airport",
			   "city": "Berlin",
			   "countryCode": "DE",
			   "countryName": "Germany",
			   "regionName": "Europe",
			   "timeZoneRegionName": "Europe/Berlin",
			   "localTime": "2013-04-20T19:50:25.643",
			   "utcOffsetHours": 2,
			   "latitude": 52.366667,
			   "longitude": 13.503333,
			   "elevationFeet": 154,
			   "classification": 2,
			   "active": true,
			   "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BER?codeType=fs",
			   "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BER?codeType=fs"
			  },
			  {
			   "fs": "FMM",
			   "iata": "FMM",
			   "icao": "EDJA",
			   "name": "Memmingen Airport",
			   "city": "Memmingen",
			   "countryCode": "DE",
			   "countryName": "Germany",
			   "regionName": "Europe",
			   "timeZoneRegionName": "Europe/Berlin",
			   "localTime": "2013-04-20T19:50:25.643",
			   "utcOffsetHours": 2,
			   "latitude": 47.988611,
			   "longitude": 10.239444,
			   "elevationFeet": 2076,
			   "classification": 4,
			   "active": true,
			   "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/FMM?codeType=fs",
			   "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/FMM?codeType=fs"
			  },
			  {
			   "fs": "BRE",
			   "iata": "BRE",
			   "icao": "EDDW",
			   "name": "Bremen Airport",
			   "city": "Bremen",
			   "cityCode": "BRE",
			   "countryCode": "DE",
			   "countryName": "Germany",
			   "regionName": "Europe",
			   "timeZoneRegionName": "Europe/Berlin",
			   "localTime": "2013-04-20T19:50:25.643",
			   "utcOffsetHours": 2,
			   "latitude": 53.052971,
			   "longitude": 8.785352,
			   "elevationFeet": 13,
			   "classification": 3,
			   "active": true,
			   "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BRE?codeType=fs",
			   "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BRE?codeType=fs"
			  },
			  {
			   "fs": "TXL",
			   "iata": "TXL",
			   "icao": "EDDT",
			   "name": "Tegel Airport",
			   "city": "Berlin",
			   "cityCode": "BER",
			   "countryCode": "DE",
			   "countryName": "Germany",
			   "regionName": "Europe",
			   "timeZoneRegionName": "Europe/Berlin",
			   "localTime": "2013-04-20T19:50:25.643",
			   "utcOffsetHours": 2,
			   "latitude": 52.553944,
			   "longitude": 13.291722,
			   "elevationFeet": 121,
			   "classification": 1,
			   "active": true,
			   "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/TXL?codeType=fs",
			   "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/TXL?codeType=fs"
			  },
			  {
			   "fs": "HOQ",
			   "iata": "HOQ",
			   "icao": "EDQM",
			   "name": "Hof Airport",
			   "city": "Hof",
			   "cityCode": "HOQ",
			   "countryCode": "DE",
			   "countryName": "Germany",
			   "regionName": "Europe",
			   "timeZoneRegionName": "Europe/Berlin",
			   "localTime": "2013-04-20T19:50:25.643",
			   "utcOffsetHours": 2,
			   "latitude": 50.289167,
			   "longitude": 11.862222,
			   "elevationFeet": 1958,
			   "classification": 4,
			   "active": true,
			   "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/HOQ?codeType=fs",
			   "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/HOQ?codeType=fs"
			  },
			  {
			   "fs": "MHG",
			   "iata": "MHG",
			   "icao": "EDFM",
			   "name": "Mannheim Airport",
			   "city": "Mannheim",
			   "cityCode": "MHG",
			   "countryCode": "DE",
			   "countryName": "Germany",
			   "regionName": "Europe",
			   "timeZoneRegionName": "Europe/Berlin",
			   "localTime": "2013-04-20T19:50:25.643",
			   "utcOffsetHours": 2,
			   "latitude": 49.476577,
			   "longitude": 8.521081,
			   "elevationFeet": 309,
			   "classification": 4,
			   "active": true,
			   "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/MHG?codeType=fs",
			   "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/MHG?codeType=fs"
			  }]
			  ;	
airport[7]	= [
				{
			   "fs": "CROWDEDSKY",
			   "iata": "BER",
			   "name": "The Crowded Sky",
			   "city": "Berlin",
			   "countryCode": "DE",
			   "countryName": "Germany",
			   "regionName": "Europe",
			   "timeZoneRegionName": "Europe/Berlin",
			   "localTime": "2013-04-20T19:50:25.643",
			   "utcOffsetHours": 2,
			   "latitude": 52.366667,
			   "longitude": 13.503333,
			   "elevationFeet": 154,
			   "classification": 2,
			   "active": true,
			   "url" : "http://planefinder.net/" 
			  },
			   {
			   "fs": "BER",
			   "iata": "BER",
			   "name": "Airline Fleet",
			   "city": "Berlin",
			   "countryCode": "DE",
			   "countryName": "Germany",
			   "regionName": "Europe",
			   "timeZoneRegionName": "Europe/Berlin",
			   "localTime": "2013-04-20T19:50:25.643",
			   "utcOffsetHours": 2,
			   "latitude": 52.366667,
			   "longitude": 13.503333,
			   "elevationFeet": 154,
			   "classification": 2,
			   "active": true,
			   "url" : "http://www.flightradar24.com/data/airplanes/" 
			  },
			  {
			   "fs": "BER",
			   "iata": "BER",
			   "name": "World Airport",
			   "city": "Berlin",
			   "countryCode": "DE",
			   "countryName": "Germany",
			   "regionName": "Europe",
			   "timeZoneRegionName": "Europe/Berlin",
			   "localTime": "2013-04-20T19:50:25.643",
			   "utcOffsetHours": 2,
			   "latitude": 52.366667,
			   "longitude": 13.503333,
			   "elevationFeet": 154,
			   "classification": 2,
			   "active": true,
			   "url" : "http://www.flightradar24.com/data/airports/" 
			  },
			  {
			   "fs": "BER",
			   "iata": "BER",
			   "name": "Search Anything on the Sky",
			   "city": "Berlin",
			   "countryCode": "DE",
			   "countryName": "Germany",
			   "regionName": "Europe",
			   "timeZoneRegionName": "Europe/Berlin",
			   "localTime": "2013-04-20T19:50:25.643",
			   "utcOffsetHours": 2,
			   "latitude": 52.366667,
			   "longitude": 13.503333,
			   "elevationFeet": 154,
			   "classification": 2,
			   "active": true,
			   "url" : "http://www.flightradar24.com/data/" 
			  },
			  
			  ];
			  			  		  		  		  	  